name: CI

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Linux build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        mkdir ../build
        cd ../build
        cmake -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DMOX_TESTS=ON ../mox
    - name: Build debug
      run: |
        cmake -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_GTEST=ON -DMOX_TESTS=ON ../mox
        cmake --build . --config Debug --target unittest -- -j4
    - name: Run unit tests
      run: |
        cd tests
        ./unittest

